// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
    public static void main(String[] args) {


        int n = Integer.parseInt(args[0]);

		double a = 0.0;
		double greater =0.0;
		double smaller =0.0;


		for(int i=0; i<n ; i++){
			a =(Math.random() *(1));

			if(a>0.5){
				greater++;
			}
			else{
				smaller++;
			}
		}
		System.out.println(greater +"  "   + smaller);
		if(greater ==0 || smaller ==0){
            System.out.println("Error");
		}
		else if(greater > smaller){
			System.out.println(smaller/greater);

		}
		else{
			System.out.println(greater/smaller);
		}

	}
}
